# 配置文件

[input]
path = "."
ignored = ["ignored", "output"]
moveFail = true

[output]
path = 'output/{year}/{num}'

[proxy]
## proxy [socks5://][127.0.0.1:]<1-65535>;
## 协议：socks4, socks5, http, https
socket = ""
enable = false

[DMMApi]
apiId = ""
affiliateId = ""

[translate]
enable = true
apiUrl = ""
apiKey = ""

model = "gpt-4o-mini"

temparature = 0.1
topP = 0.5
maxTokens = 1024

SystemPrompt = """
You are a translator, you will translate the text in the input to the target language.
"""