name: Build and Release Go Binaries
on:
    push:
        tags:
            - "v*"
jobs:
    build:
        name: Build Release Assets
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version-file: "go.mod"

            - name: Build binaries
              run: |
                  GOOS=linux GOARCH=amd64 go build -trimpath -ldflags '-w -s' -o bin/jav-scraper-linux-amd64
                  GOOS=windows GOARCH=amd64 go build -trimpath -ldflags '-w -s' -o bin/jav-scraper-windows-amd64.exe

            - name: Create Release
              uses: softprops/action-gh-release@v1
              with:
                  files: |
                      bin/jav-scraper-linux-amd64
                      bin/jav-scraper-windows-amd64.exe
